<script setup lang="ts">
import AppLayout from '@/layouts/AppLayout.vue';
import { type BreadcrumbItem } from '@/types';
import { Head, Link, router } from '@inertiajs/vue3';
import { ArrowLeft, Download, HardHat, PackageCheck } from 'lucide-vue-next';
const props=defineProps<{transfer:any}>();
const breadcrumbs:BreadcrumbItem[]=[{title:'Transferts chantiers',href:route('transfers.index')},{title:props.transfer.transfer_number || `Bon #${props.transfer.id}`,href:'#'}];
const qty=(v:any)=>new Intl.NumberFormat('fr-FR',{maximumFractionDigits:2}).format(Number(v));
const date=(v:string)=>new Date(v).toLocaleDateString('fr-FR',{day:'2-digit',month:'long',year:'numeric'});
const cancel=()=>{const reason=window.prompt('Motif obligatoire de l’annulation :');if(reason)router.post(route('transfers.cancel',props.transfer.id),{reason})};
const confirmDraft=()=>router.post(route('transfers.confirm',props.transfer.id));
const signDispatch=()=>router.post(route('transfers.sign-dispatch',props.transfer.id));
const signSite=()=>router.post(route('transfers.sign-site',props.transfer.id));
</script>
<template><Head :title="transfer.transfer_number || `Bon de transfert #${transfer.id}`"/><AppLayout :breadcrumbs="breadcrumbs"><div class="mx-auto max-w-5xl p-4 sm:p-6"><div class="mb-5 flex flex-wrap items-start justify-between gap-3"><div class="flex gap-3"><Link :href="route('transfers.index')" class="rounded-xl border bg-white p-2"><ArrowLeft class="h-5 w-5"/></Link><div><div class="flex items-center gap-2"><p class="text-xs font-semibold uppercase text-amber-700">Bon de transfert</p><span class="rounded-full px-2 py-0.5 text-[10px] font-bold uppercase" :class="transfer.status==='confirmed'?'bg-emerald-100 text-emerald-700':transfer.status==='cancelled'?'bg-red-100 text-red-700':'bg-amber-100 text-amber-700'">{{transfer.status}}</span></div><h1 class="text-2xl font-bold">{{ transfer.transfer_number || ('BT-' + String(transfer.id).padStart(6, '0')) }}</h1></div></div><div class="flex flex-wrap gap-2"><button v-if="transfer.status==='draft'" class="rounded-xl bg-emerald-600 px-4 py-2.5 font-semibold text-white" @click="confirmDraft">Confirmer</button><Link v-if="transfer.status==='draft'" :href="route('transfers.edit',transfer.id)" class="rounded-xl border border-amber-500 px-4 py-2.5 font-semibold text-amber-700">Reprendre</Link><button v-if="transfer.status!=='cancelled'" class="rounded-xl border border-red-300 px-4 py-2.5 font-semibold text-red-700" @click="cancel">Annuler</button><a :href="route('transfers.pdf',transfer.id)" class="flex items-center gap-2 rounded-xl bg-slate-900 px-4 py-2.5 font-semibold text-white"><Download class="h-4 w-4"/>Télécharger PDF</a><button class="rounded-xl border px-4 py-2.5 font-semibold" @click="window.open(route('transfers.pdf',{transfer:transfer.id,print:1}),'_blank')">Imprimer</button></div></div>
<section class="grid gap-4 rounded-2xl border bg-white p-5 shadow-sm md:grid-cols-2"><div><p class="text-xs uppercase text-slate-500">Chantier destination</p><p class="mt-1 flex items-center gap-2 font-bold"><HardHat class="h-4 w-4 text-amber-600"/>{{transfer.project?.code}} — {{transfer.project?.name}}</p></div><div><p class="text-xs uppercase text-slate-500">Date du transfert</p><p class="mt-1 font-semibold">{{date(transfer.transferred_at)}}</p></div><div><p class="text-xs uppercase text-slate-500">Réception / Bon de commande</p><Link :href="route('purchase-orders.show',transfer.reception.purchase_order.id)" class="mt-1 block font-semibold text-blue-700">{{transfer.reception.purchase_order.order_number||transfer.reception.purchase_order.title}}</Link></div><div><p class="text-xs uppercase text-slate-500">Référence sortie</p><p class="mt-1 font-semibold">{{transfer.reference||'—'}}</p></div><div><p class="text-xs uppercase text-slate-500">Effectué par</p><p class="mt-1 font-semibold">{{transfer.actor?.name||'—'}}</p></div><div><p class="text-xs uppercase text-slate-500">Notes</p><p class="mt-1">{{transfer.notes||'—'}}</p></div></section>
<section class="mt-5 overflow-hidden rounded-2xl border bg-white shadow-sm"><div class="flex items-center gap-2 border-b px-5 py-4 font-bold"><PackageCheck class="h-5 w-5 text-amber-600"/>Articles transférés ({{transfer.lines.length}})</div><table class="w-full text-sm"><thead class="bg-slate-50 text-left text-xs uppercase text-slate-500"><tr><th class="px-5 py-3">Article</th><th class="px-5 py-3 text-right">Quantité</th></tr></thead><tbody class="divide-y"><tr v-for="line in transfer.lines" :key="line.id"><td class="px-5 py-4"><strong>{{line.reception_line?.order_line?.article?.name||'Article'}}</strong><p v-if="line.reception_line?.order_line?.article?.reference" class="font-mono text-xs text-slate-500">{{line.reception_line.order_line.article.reference}}</p><p v-if="line.reception_line?.order_line?.note" class="text-xs italic text-slate-500">{{line.reception_line.order_line.note}}</p></td><td class="px-5 py-4 text-right font-bold">{{qty(line.quantity_transferred)}} {{line.reception_line?.order_line?.article?.unit}}</td></tr></tbody></table></section><section class="mt-5 grid gap-4 md:grid-cols-2"><div class="rounded-2xl border bg-white p-5"><h3 class="font-bold">Responsable de sortie</h3><p class="text-sm text-slate-600">{{transfer.actor?.name}}</p><p class="mt-2 text-sm" :class="transfer.dispatch_signed_at?'text-emerald-700':'text-amber-700'">{{transfer.dispatch_signed_at?'Signé':'Signature en attente'}}</p><button v-if="!transfer.dispatch_signed_at&&transfer.status==='confirmed'" class="mt-3 rounded-xl bg-slate-900 px-4 py-2 text-white" @click="signDispatch">Signer la sortie</button></div><div class="rounded-2xl border bg-white p-5"><h3 class="font-bold">Responsable chantier</h3><p class="text-sm text-slate-600">{{transfer.project_responsible?.name||'Non défini'}}</p><p class="mt-2 text-sm" :class="transfer.site_signed_at?'text-emerald-700':'text-amber-700'">{{transfer.site_signed_at?'Signé':'Signature en attente'}}</p><button v-if="!transfer.site_signed_at&&transfer.status==='confirmed'" class="mt-3 rounded-xl bg-amber-600 px-4 py-2 text-white" @click="signSite">Signer la réception</button></div></section><div v-if="transfer.status==='cancelled'" class="mt-5 rounded-xl border border-red-200 bg-red-50 p-4 text-red-800"><strong>Bon annulé :</strong> {{transfer.cancellation_reason}}</div></div></AppLayout></template>